name        'garethr-golang'
version     '0.0.3'
source      'git://github.com/garethr/garethr-golang.git'
author      'Gareth Rushgrove'
summary     'Module for installing go from official ppa'
description 'Install one of the official golang packages'
license     'Apache License, Version 2.0'
dependency  'puppetlabs/apt'
dependency  'puppetlabs/stdlib'
